### ISSUE TITLE
React-native Onfido SDK: Deprecated API issue

### ISSUE THREAD

**Issue by trdevendran** [MCROEngineering/react-native-onfido-sdk#7]
Hi guys, I have perfectly followed your documentation and done the setup but facing an issue while running out with below error,

<h3>Android studio throws error as below:</h3>
> node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.
Some input files use unchecked or unsafe operations.
Recompile with -Xlint:unchecked for details.

<h3>Terminal throws error as below:</h3>
>FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-onfido-sdk:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

BUILD FAILED in 12s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (App-2.0/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (App-2.0/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at then.result (App-2.0/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:125:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by AndriiChubariev** [comment]
Hey guys, it would be super helpful if you could upload a new example with the latest react native (0.61 at this point) and the latest onfido sdk.

The existing example is totally broken and outdated.
